### ISSUE TITLE
compatible with debian?

### ISSUE THREAD

**Issue by buzucan** [VirtuBox/wo-nginx-setup#2]
hello, this version of WO will be compatible with Debian 8 or 9? There is any chance?

**Comment by VirtuBox** [comment]
Hello @buzucan,

At the moment, this bash script is only compatible with Ubuntu 16/18.04 LTS, and Debian support isn't planned. 

Here few reasons : 

* There is no official LTS on Debian 
Debian 8 already reached its EOL in June 2018 and Debian 9 EOL will probably be in June 2020.
Ubuntu 16.04 LTS will be supported until 2021, and Ubuntu 18.04 LTS until 2023.

* On Ubuntu, most part of up-to-date packages can be found on launchpad PPA (GCC-8, Redis 5.0, ffmpeg 4 etc..). But PPA are not available on Debian. So it's pretty painful to have to compile each package from source to get an up-to-date version. 

* Ubuntu provide several cool features like snap or lxd
