### ISSUE TITLE
errors execution script

### ISSUE THREAD

**Issue by juanpvh** [VirtuBox/wo-nginx-setup#3]
hello @VirtuBox I know that you are working at this moment in this project, we are happy with your commitment.

To test the script some errors that may help you.

#wo stack install:
not install phpmyadmin 
,adminer not install
#Downloading Adminer              Unable to download file, /var/www/22222/htdocs/db/adminer/index.php

#directory not create
##########################################
 Configuring Nginx
##########################################
cp: target '/etc/nginx/common/' is not a directory

####################################
Checking Nginx configuration
####################################
####################################
Reloading Nginx
####################################
####################################
Reloading UFW
####################################
Firewall not enabled (skipping reload)
[master 6a4d25e] update nginx.conf and setup cloudflare visitor real IP restore
 2 files changed, 190 insertions(+), 142 deletions(-)
 rewrite nginx.conf (83%)
grep: /etc/nginx/sites-available/22222: No such file or directory

root@vultr:~/wo-nginx-setup# wo --version
WordOps v3.9.2
Copyright (c) 2018 WordOps.
root@vultr:~/wo-nginx-setup#

the lack of common folder is impossible to create redis sites

**Comment by juanpvh** [comment]
mysql 

Feb 24 13:21:41 vultr.guest /etc/mysql/debian-start[22774]: Checking for insecure root accounts.
Feb 24 13:21:41 vultr.guest /etc/mysql/debian-start[22778]: Triggering myisam-recover for all MyISAM tables and aria-recover for all Aria tables
Feb 24 13:40:38 vultr.guest mysqld[22714]: 2019-02-24 13:40:38 38 [Warning] Access denied for user 'netdata'@'localhost' (using password: NO)
Feb 24 13:40:38 vultr.guest mysqld[22714]: 2019-02-24 13:40:38 40 [Warning] Access denied for user 'stats'@'localhost' (using password: YES)
Feb 24 13:40:38 vultr.guest mysqld[22714]: 2019-02-24 13:40:38 41 [Warning] Access denied for user 'admin'@'localhost' (using password: YES)
Feb 24 13:40:41 vultr.guest mysqld[22714]: 2019-02-24 13:40:41 39 [Warning] Aborted connection 39 to db: 'unconnected' user: 'root' host: 'localhost' (Got an error rea
Feb 24 13:40:44 vultr.guest mysqld[22714]: 2019-02-24 13:40:44 46 [Warning] Access denied for user 'stats'@'localhost' (using password: YES)
Feb 24 13:40:44 vultr.guest mysqld[22714]: 2019-02-24 13:40:44 47 [Warning] Access denied for user 'admin'@'localhost' (using password: YES)
Feb 24 14:20:41 vultr.guest mysqld[22714]: 2019-02-24 14:20:41 65 [Warning] Aborted connection 65 to db: 'wopredis_servicodigital_info' user: 'root' host: 'localhost'

**Comment by VirtuBox** [comment]
> the lack of common folder is impossible to create redis sites

Hello @juanpvh,
I don't know what happened this week-end (I'm still investigating on this issue), but WordOps command "wo stack install" wasn't working properly, and it wasn't possible to deploy nginx templates.
I had exactly the same issue on all my travis build and on my testing servers.
But since this morning, everything is working properly and this issue should not happen if you run my script again on a fresh installation.

About failed login to mysql with netdata user, issue come from the variable used by the interactive installation, it will be fixed soon.

**Comment by jaurochan** [comment]
and what is th username and password for netdata?

**Comment by nsgoyat** [comment]
@jaurochan Try using the User and Password combo from the file `/etc/nginx/htpasswd-wo`

You can always generate a new User/Pass pair using the command `wo secure --auth`

**Comment by jaurochan** [comment]
Ok but after created ssl with ee-acme (all dns record created) still get 403 when i try to login to 22222 admin page even after changed username and password with wo secure --auth

**Comment by jaurochan** [comment]
Ok now it woks.
One question: i seee this on my nginx error.log

2019/03/07 09:33:50 [crit] 33920#33920: *2 connect() to unix:/run/php/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: 127.0.0.1, request: "GET /status?full&json HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "localhost"
