### ISSUE TITLE
running script with root

### ISSUE THREAD

**Issue by juanpvh** [VirtuBox/wo-nginx-setup#4]
@virtubox all right ?!

I need to run the wo-nginx-setup script without these lines:

##################################
# SSH Keys check
##################################

if [-d $ HOME / .ssh]; then
     ecdsa_keys_check = $ (grep "ecdsa-sha2" -r $ HOME / .ssh)
     rsa_keys_check = $ (grep "ssh-rsa" -r $ HOME / .ssh)
     ed25519_keys_check = $ (grep "ssh-ed25519" -r $ HOME / .ssh)
     if [-z "$ ecdsa_keys_check"] && [-z "$ rsa_keys_check"] && [-z "$ ed25519_keys_check"]; then
         echo "This script requires to use ssh keys authentification. Please make sure you have properly added your public ssh keys into .ssh / authorized_keys"
         exit 1
     fi
else
     echo "This script requires to use ssh keys authentification. Please make sure you have properly added your public ssh keys into .ssh / authorized_keys"
     exit 1
fi

I removed the same from the script, however when the installation and finished wordops is not installed.
Do I need to remove any others to succeed in the root installation?

**Comment by VirtuBox** [comment]
Hello @juanpvh,
I have just pushed few changes on the repository, mostly to remove features available in WordOps, and as you can see on the travis build details, WordOps was successfully installed : https://travis-ci.org/VirtuBox/wo-nginx-setup/builds/516876091

**Comment by juanpvh** [comment]
netdata and acme embedded in wordops &#x1F64C; &#x1F64C;
