### ISSUE TITLE
Extplorer correct link download

### ISSUE THREAD

**Issue by juanpvh** [VirtuBox/wo-nginx-setup#7]
https://github.com/VirtuBox/wo-nginx-setup/blob/eb0173ead92efa6523f8d7b2b0e4a650878aad40/wo-nginx-setup.sh#L841

https://extplorer.net/attachments/download/78/eXtplorer_2.1.12.zip

**Comment by VirtuBox** [comment]
Issue has been fixed with PR https://github.com/VirtuBox/wo-nginx-setup/pull/8
